apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mercadolibre-data
  namespace: mercadolibre-monitor
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path  # Ajustar según tu storageClass en RKE2
