{{- if and (not .Values.existingSecret) (or .Values.notifications.slack.enabled .Values.notifications.discord.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "meli-monitor.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "meli-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.notifications.slack.enabled }}
  slack-webhook: {{ .Values.notifications.slack.webhook | quote }}
  {{- end }}
  {{- if .Values.notifications.discord.enabled }}
  discord-webhook: {{ .Values.notifications.discord.webhook | quote }}
  {{- end }}
{{- end }}
